# Hackintosh Kext Release
trigger: none
pr: none

schedules:
- cron: "0 0 * * *"
  displayName: Schedule Build
  branches:
    include:
    - master
  always: true

pool:
  vmImage: 'macOS-latest'

steps:
- task: Bash@3
  displayName: 'Lilu Basic Dependency'
  inputs:
    targetType: 'inline'
    script: |
      #!/bin/bash
      BD="$(date +"%Y-%m-%d")"
      echo "##vso[task.setvariable variable=BuildDate]$BD"
      mkdir -p release/Lilu
      mkdir -p release/VoodooInput
      git clone -q https://github.com/acidanthera/MacKernelSDK.git

      echo "==========================================================================="
      echo "========================> Building Lilu Dependency <======================="
      echo "==========================================================================="
      git clone -q https://github.com/ChefKissInc/NootedRed.git && cd NootedRed
      cp -r ../MacKernelSDK .
      xcodebuild -configuration Debug > /dev/null 2>&1
      xcodebuild -configuration Release > /dev/null 2>&1
      cd ..
      cp NootedRed/build/*/*.zip release/NootedRed/

    title: Hackintosh-Kext🚀 | 自动编译 / $(BuildDate)
    releaseNotesFile: releaseNotesFile.md
    assets: '$(Build.ArtifactStagingDirectory)/*.zip'
